name: Check Links

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  awesome_bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install awesome_bot
      run: gem install awesome_bot
    - name: Run awesome_bot
      run: awesome_bot README.md --allow-redirect --allow-dupe --set-timeout 60 --skip-save-results --allow 429
